DROP TABLE IF EXISTS FACT_NAF_CODES CASCADE;
CREATE TABLE FACT_NAF_CODES (
    NAF_CODE    VARCHAR(5) NOT NULL UNIQUE PRIMARY KEY,
    TITLE       TEXT,
    TITLE_65    VARCHAR(65),
    TITLE_40    VARCHAR(40)
);
