DROP TABLE IF EXISTS NAF_CODES CASCADE;

CREATE UNLOGGED TABLE NAF_CODES (
    NAF_CODE    VARCHAR(5) NOT NULL UNIQUE PRIMARY KEY,
    TITLE       TEXT,
    TITLE_65    VARCHAR(65),
    TITLE_40    VARCHAR(40)
);
