DROP TABLE IF EXISTS FACT_HISTORICAL_COMPANIES CASCADE;
CREATE TABLE FACT_HISTORICAL_COMPANIES (
    ID                                          SERIAL PRIMARY KEY NOT NULL,
    SIREN                                       VARCHAR(9) NOT NULL,
    NIC                                         VARCHAR(5) NOT NULL,
    SIRET                                       VARCHAR(14) NOT NULL,
    END_DATE                                    DATE,
    BEGIN_DATE                                  DATE,
    INSTITUTION_ADMINISTRATIVE_STATE            VARCHAR(1),
    INSTITUTION_ADMINISTRATIVE_STATE_CHANGE     BOOLEAN,
    INSTITUTION_1_NAME                          TEXT,
    INSTITUTION_2_NAME                          TEXT,
    INSTITUTION_3_NAME                          TEXT,
    INSTITUTION_NAME_CHANGE                     BOOLEAN,
    INSTITUTION_USUAL_NAME                      TEXT,
    INSTITUTION_USUAL_NAME_CHANGE               BOOLEAN,
    INSTITUTION_PRIMARY_ACTIVITY                VARCHAR(6),
    INSTITUTION_PRIMARY_ACTIVITY_NOMENCLATURE   VARCHAR(8),
    INSTITUTION_PRIMARY_ACTIVITY_CHANGE         BOOLEAN,
    INSTITUTION_EMPLOYER_NATURE                 VARCHAR(1) NOT NULL,
    INSTITUTION_EMPLOYER_NATURE_CHANGE          BOOLEAN
);

CREATE INDEX ON FACT_HISTORICAL_COMPANIES(SIREN, NIC, SIRET);
CREATE INDEX ON FACT_HISTORICAL_COMPANIES(SIREN);
CREATE INDEX ON FACT_HISTORICAL_COMPANIES(NIC);
CREATE INDEX ON FACT_HISTORICAL_COMPANIES(SIRET);
CREATE INDEX ON FACT_HISTORICAL_COMPANIES(INSTITUTION_ADMINISTRATIVE_STATE);
CREATE INDEX ON FACT_HISTORICAL_COMPANIES(INSTITUTION_PRIMARY_ACTIVITY);
CREATE INDEX ON FACT_HISTORICAL_COMPANIES(INSTITUTION_PRIMARY_ACTIVITY_NOMENCLATURE);
CREATE INDEX ON FACT_HISTORICAL_COMPANIES(INSTITUTION_EMPLOYER_NATURE);
