DROP TABLE IF EXISTS COMPANY;

CREATE TABLE COMPANY (
    ID                                          SERIAL PRIMARY KEY NOT NULL,
    SIREN                                       VARCHAR(9) NOT NULL,
    NIC                                         VARCHAR(5) NOT NULL,
    SIRET                                       VARCHAR(14) NOT NULL,
    COMPANY_DIFFUSION_STATUT                    VARCHAR(1),
    COMPANY_CREATION_DATE                       DATE,
    COMPANY_STAFF_NUMBER_RANGE                  VARCHAR(2),
    COMPANY_STAFF_NUMBER_YEAR                   SMALLINT,
    COMPANY_PRINCIPAL_REGISTERED_ACTIVITY       VARCHAR(6),
    COMPANY_LAST_PROCESSING                     TIMESTAMP WITHOUT TIME ZONE,
    COMPANY_IS_HEADQUARTERS                     BOOLEAN,
    COMPANY_PERIOD_COUNT                        SMALLINT,
    COMPANY_ADDRESS_COMPLEMENT                  VARCHAR(38),
    COMPANY_ADDRESS_STREET_NUMBER               VARCHAR(4),
    COMPANY_ADDRESS_STREET_NUMBER_REPETITION    VARCHAR(1),
    COMPANY_ADDRESS_STREET_TYPE                 VARCHAR(4),
    COMPANY_ADDRESS_STREET_NAME                 VARCHAR(100),
    COMPANY_ADDRESS_POSTAL_CODE                 VARCHAR(5),
    COMPANY_ADDRESS_CITY                        VARCHAR(100),
    COMPANY_FOREIGN_ADDRESS_CITY                VARCHAR(100),
    COMPANY_ADDRESS_SPECIAL_DISTRIBUTION        VARCHAR(26),
    COMPANY_ADDRESS_CITY_CODE                   VARCHAR(5),
    COMPANY_ADDRESS_CEDEX_CODE                  VARCHAR(9),
    COMPANY_ADDRESS_CEDEX_NAME                  VARCHAR(100),
    COMPANY_FOREIGN_ADDRESS_COUNTRY_CODE        VARCHAR(5),
    COMPANY_FOREIGN_ADDRESS_COUNTRY_NAME        VARCHAR(100),
    COMPANY_ADDRESS_COMPLEMENT_2                VARCHAR(38),
    COMPANY_ADDRESS_STREET_NUMBER_2             VARCHAR(4),
    COMPANY_ADDRESS_STREET_NUMBER_REPETITION_2  VARCHAR(1),
    COMPANY_ADDRESS_STREET_TYPE_2               VARCHAR(4),
    COMPANY_ADDRESS_STREET_NAME_2               VARCHAR(100),
    COMPANY_ADDRESS_POSTAL_CODE_2               VARCHAR(5),
    COMPANY_ADDRESS_CITY_2                      VARCHAR(100),
    COMPANY_FOREIGN_ADDRESS_CITY_2              VARCHAR(100),
    COMPANY_ADDRESS_SPECIAL_DISTRIBUTION_2      VARCHAR(26),
    COMPANY_ADDRESS_CITY_CODE_2                 VARCHAR(5),
    COMPANY_ADDRESS_CEDEX_CODE_2                VARCHAR(9),
    COMPANY_ADDRESS_CEDEX_NAME_2                VARCHAR(100),
    COMPANY_FOREIGN_ADDRESS_COUNTRY_CODE_2      VARCHAR(5),
    COMPANY_FOREIGN_ADDRESS_COUNTRY_NAME_2      VARCHAR(100),
    BEGIN_DATE                                  DATE,
    COMPANY_ADMINISTATIVE_STATE                 VARCHAR(1),
    COMPANY_NAME_1                              VARCHAR(50),
    COMPANY_NAME_2                              VARCHAR(50),
    COMPANY_NAME_3                              VARCHAR(50),
    COMPANY_USUAL_NAME                          VARCHAR(100),
    COMPANY_ACTIVITY                            VARCHAR(6),
    COMPANY_PRINCIPAL_ACTIVITY_NAME             VARCHAR(8),
    COMPANY_IS_EMPLOYER                         VARCHAR(1)
);

CREATE INDEX ON COMPANY(SIREN);
CREATE INDEX ON COMPANY(NIC);
CREATE INDEX ON COMPANY(SIRET);
CREATE INDEX ON COMPANY(COMPANY_USUAL_NAME);
CREATE INDEX ON COMPANY(COMPANY_ACTIVITY);
CREATE INDEX ON COMPANY(COMPANY_PRINCIPAL_ACTIVITY_NAME);
