DROP TABLE IF EXISTS COMPANY_LEGAL_UNIT_HISTORY;

CREATE UNLOGGED TABLE COMPANY_LEGAL_UNIT_HISTORY (
    SIREN                                                 VARCHAR(9),
    END_DATE                                              DATE,
    BEGIN_DATE                                            DATE,
    LEGAL_UNIT_ADMINISTRATIVE_STATE                       VARCHAR(1),
    LEGAL_UNIT_ADMINISTRATIVE_STATE_CHANGE                BOOLEAN,
    LEGAL_UNIT_LEGAL_UNIT_NAME                            VARCHAR(100),
    LEGAL_UNIT_LEGAL_UNIT_NAME_CHANGE                     BOOLEAN,
    LEGAL_UNIT_USUAL_NAME                                 VARCHAR(100),
    LEGAL_UNIT_USUAL_NAME_CHANGE                          BOOLEAN,
    LEGAL_UNIT_DENOMINATION                               VARCHAR(120),
    LEGAL_UNIT_DENOMINATION_CHANGE                        BOOLEAN,
    LEGAL_UNIT_USUAL_DENOMINATION_1                       VARCHAR(70),
    LEGAL_UNIT_USUAL_DENOMINATION_2                       VARCHAR(70),
    LEGAL_UNIT_USUAL_DENOMINATION_3                       VARCHAR(70),
    LEGAL_UNIT_USUAL_DENOMINATION_CHANGE                  BOOLEAN,
    LEGAL_UNIT_LEGAL_CATEGORY                             VARCHAR(16),
    LEGAL_UNIT_LEGAL_CATEGORY_CHANGE                      BOOLEAN,
    LEGAL_UNIT_PRINCIPAL_ACTIVITY                         VARCHAR(6),
    LEGAL_UNIT_PRINCIPAL_ACTIVITY_NOMENCLATURE            VARCHAR(8),
    LEGAL_UNIT_PRINCIPAL_ACTIVITY_NOMENCLATURE_CHANGE     BOOLEAN,
    LEGAL_UNIT_HEADQUARTER_NIC                            VARCHAR(5),
    LEGAL_UNIT_HEADQUARTER_NIC_CHANGE                     BOOLEAN,
    LEGAL_UNIT_IS_SOCIAL_AND_SOLIDARITY_ECONOMY           VARCHAR(1),
    LEGAL_UNIT_IS_SOCIAL_AND_SOLIDARITY_ECONOMY_CHANGE    BOOLEAN,
    LEGAL_UNIT_IS_EMPLOYER                                VARCHAR(1),
    LEGAL_UNIT_IS_EMPLOYER_CHANGE                         BOOLEAN
);

CREATE INDEX ON COMPANY_LEGAL_UNIT_HISTORY(SIREN);
